### ISSUE TITLE
Renaming is applying after CommonsChunkPlugin actions

### ISSUE THREAD

**Issue by unlight** [Independer/angular-named-lazy-chunks-webpack-plugin#1]
CommonsChunkPlugin doesnot work with option `chunks: string[]` (extract common from selected chunks), due to [subj] CommonsChunkPlugin cannot find selected chunks.

Is it possible to apply renaming BEFORE CommonsChunkPlugin actions?

**Comment by shaungrady** [comment]
Change the order of the plugins in your webpack config. Try moving `CommonsChunkPlugin` to the end of the `plugins` array.

**Comment by unlight** [comment]
Order does not matter.

**Comment by IAMtheIAM** [comment]
Order DOES matter with webpack plugins. They run in a sync series.

**Comment by unlight** [comment]
It does matter only if they subscribes to same events.
```
webpack\lib\Compiler.js:
this.applyPlugins("this-compilation", compilation, params);
this.applyPlugins("compilation", compilation, params);
```
NamedChunksPlugin subscribes to `compilation` event.
CommonsChunkPlugin.js subscribes to `this-compilation`

Thus and so, `this-compilation` plugins will be always applied after `compilation` plugins, no matter where it's positions in `webpack.config.plugins`.

**Comment by pglazkov** [comment]
This issue is out of scope of this plugin since it only extends Webpack's own `NamedChunksPlugin` and it doesn't control when it is applied.
