### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by kenborge** [Independer/angular-named-lazy-chunks-webpack-plugin#5]
Has anyone tried this plugin with angular 6? For me it's causing issues with lazy loaded modules not resolving properly, some parts of them seem to be missing, so you get errors that modules can't be resolved. 

So far I have a theory it can be related to chunk splitting when building for production(only happens with --mode production), but have not been able to pin down the reason yet.

**Comment by pglazkov** [comment]
I did try it on one of the projects and it seems to work. Could you provide a sample project to help reproduce the problem you're seeing? 

Also note that `AngularCompilerPlugin` now has a `nameLazyFiles` setting:

```js
new AngularCompilerPlugin({
  ...
  nameLazyFiles: true
})
```

If you're using that plugin in your Webpack config, you could try that instead and see if it works for you.

**Comment by kenborge** [comment]
The project i am working on is extremely big and complex so i haven't been able to figure out what interaction causes this plugin not to work so not been able to make a minimal implementation that reproduces it. 
Wanted to see if anyone else had similar  problems.

Thanks i will checkout the  AngularCompilerPlugin flag as well

**Comment by sod** [comment]
If you use this plugin, you must set the webpack option `optimization.splitChunks.maxAsyncRequests` to `1`.
If `maxAsyncRequests` is bigger than `1` webpack may break down your chunks even further and this plugin gives those new chunks all the same name.

**Comment by arusak** [comment]
I faced the same problem. @sod is right. For complex projects webpack seems to generate a bunch of chunks with code shared between lazy modules. 

As an illustration, here's what it gave me for an app with 4 lazy modules which share some code between them. maxAsyncRequests is not set, the plugin is not used. I enabled nameLazyFiles option to make it more spectacular.

```
$ ls -1 *.js
admin-admin-module-ngfactory.27c7a3ac.chunk.js
admin-admin-module-ngfactory~doctor-doctor-module-ngfactory.6eb7f88e.chunk.js
admin-admin-module-ngfactory~doctor-doctor-module-ngfactory~operator-operator-module-ngfactory.fb72d065.chunk.js
admin-admin-module-ngfactory~doctor-doctor-module-ngfactory~operator-operator-module-ngfactory~suppo~4d9859f8.6e463be1.chunk.js
admin-admin-module-ngfactory~operator-operator-module-ngfactory.52c6502c.chunk.js
app.1b55d644.chunk.js
attend-attend-module-ngfactory.3e626b30.chunk.js
doctor-doctor-module-ngfactory.53e1566b.chunk.js
doctor-doctor-module-ngfactory~operator-operator-module-ngfactory~support-support-module-ngfactory.0e5a2c15.chunk.js
doctor-doctor-module-ngfactory~support-support-module-ngfactory.261b6a6e.chunk.js
manifest.e86f1010.js
operator-operator-module-ngfactory.5164a07e.chunk.js
polyfills.88662c9c.chunk.js
preboot.cc801d07.chunk.js
support-support-module-ngfactory.8b95f163.chunk.js
vendors~admin-admin-module-ngfactory~attend-attend-module-ngfactory~doctor-doctor-module-ngfactory~o~6a1c3511.c66ef9df.chunk.js
vendors~admin-admin-module-ngfactory.b7f6ab5c.chunk.js
vendors~admin-admin-module-ngfactory~doctor-doctor-module-ngfactory.84e71018.chunk.js
vendors~admin-admin-module-ngfactory~doctor-doctor-module-ngfactory~operator-operator-module-ngfacto~7112feb3.ce5845d6.chunk.js
vendors~admin-admin-module-ngfactory~doctor-doctor-module-ngfactory~operator-operator-module-ngfacto~a0e4eb21.1b4384ed.chunk.js
vendors~attend-attend-module-ngfactory.4d7efd94.chunk.js
```
Well this looks crazy but you can see there are many chunks generated.
With AngularNamedLazyChunksWebpackPlugin it looks like this:
```
admin.01f7cbc5.chunk.js
admin.42776b1f.chunk.js
admin.bd25ae88.chunk.js
app.ef9569a0.chunk.js
attend.92c85b05.chunk.js
attend.d2adb6cc.chunk.js
doctor.243ba197.chunk.js
doctor.32e113d4.chunk.js
doctor.36510d49.chunk.js
doctor.47a806bb.chunk.js
doctor.79cf52fa.chunk.js
doctor.7e9860ef.chunk.js
doctor.9836d56b.chunk.js
doctor.aed22b54.chunk.js
doctor.f977c10d.chunk.js
doctor.fc31d5f6.chunk.js
manifest.223b13e5.js
operator.f600c639.chunk.js
polyfills.47e1b863.chunk.js
preboot.cc801d07.chunk.js
support.e70fe83f.chunk.js
```

A then, when I run the app, it fails to load with message 'TypeError: Cannot read property 'call' of undefined' in '__webpack_require__'. It can not find some component or module or smth in its inner collection of modules, because the chunk is not loaded somehow.

When maxAsyncRequests is set to 1, the problem is gone. One chunk is generated for each lazy module.

```
admin.30e3d621.chunk.js
app.b62e56a4.chunk.js
attend.47825cd0.chunk.js
doctor.00e4cb5d.chunk.js
manifest.cbb49519.js
operator.a6f6ed48.chunk.js
polyfills.4f206e34.chunk.js
preboot.cc801d07.chunk.js
support.8ecac8ed.chunk.js
```

Maybe this should be noted in readme?
